[package]
name = "oac2024"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
crossterm = "0.28.1"
image = "0.25.5"
itertools = "0.12.0"
regex = "1.11.1"
